# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/satellite_data/bldgs.ipynb.

# %% auto 0
__all__ = ['access_v3_bldgs']

# %% ../nbs/satellite_data/bldgs.ipynb 3
import geopandas as gpd
import seaborn as sns
from shapely.geometry import Point
import json
import ee
import geemap
from datetime import datetime

ee.Authenticate()
ee.Initialize(project='ee-reutkeller')

from . import util_func as utils

# %% ../nbs/satellite_data/bldgs.ipynb 5
def access_v3_bldgs(
    path_geometry : str , #path to geometry, add r before
    crs : str ='4326',  # define crs 
    ):
  
  gdf = utils.read_gdf(geometry_path=path_geometry,crs=crs)
  fc = utils.gdf_to_featureCollection(gdf)

  buildings_v3 = ee.FeatureCollection('GOOGLE/Research/open-buildings/v3/polygons')
  
  clipped_buildings = buildings_v3.filterBounds(fc.geometry())

  gdf_results = geemap.ee_to_geopandas(clipped_buildings)

  return gdf_results

  


