# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utilities/CONSTANTS.ipynb.

# %% auto 0
__all__ = ['CLOUD_FILTER', 'CLD_PRB_THRESH', 'NIR_DRK_THRESH', 'CLD_PRJ_DIST', 'BUFFER', 'CLOUDY_PIXEL_PERCENTAGE_STR',
           'COPERNICUS_S2_CLOUD_PROBABILITY_STR', 's2_img_collection_str', 's2cloudless_str']

# %% ../nbs/utilities/CONSTANTS.ipynb 3
import geopandas as gpd
import seaborn as sns


# %% ../nbs/utilities/CONSTANTS.ipynb 5
CLOUD_FILTER = 60
CLD_PRB_THRESH = 50
NIR_DRK_THRESH = 0.15
CLD_PRJ_DIST = 1
BUFFER = 50

CLOUDY_PIXEL_PERCENTAGE_STR='CLOUDY_PIXEL_PERCENTAGE'
COPERNICUS_S2_CLOUD_PROBABILITY_STR='COPERNICUS/S2_CLOUD_PROBABILITY'

# %% ../nbs/utilities/CONSTANTS.ipynb 6
#S2 image collection
s2_img_collection_str='COPERNICUS/S2_SR_HARMONIZED'
s2cloudless_str='s2cloudless'

