# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/projects/fire_detection.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/projects/fire_detection.ipynb 3
import geopandas as gpd
import ee

#|hide
#|export

import geopandas as gpd
import seaborn as sns
from shapely.geometry import Point
import json
import ee
import geemap
from datetime import datetime

ee.Authenticate()
ee.Initialize(project='ee-reutkeller')

from . import util_func as utils
from . import const_vars as const
from . import mask_s2 as mask_s2
from . import img_sen2 as img_sen2
