# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/satellite_data/s2_masks.ipynb.

# %% auto 0
__all__ = ['get_s2_sr_cld_col', 'add_cloud_bands']

# %% ../nbs/satellite_data/s2_masks.ipynb 3
import geopandas as gpd
import seaborn as sns
from shapely.geometry import Point
import json
import ee

ee.Authenticate()
ee.Initialize(project='ee-reutkeller')

from . import util_func as utils
from . import const_vars as const

# %% ../nbs/satellite_data/s2_masks.ipynb 4
def get_s2_sr_cld_col(fc : ee.featurecollection , # FeatureCollection with geometry datata
                      start_date : str , # Start date for searching images. , 
                      end_date : str , # End date for searching images.
                      ):
    # Import and filter S2 SR.
    s2_sr_col = (ee.ImageCollection(const.s2_img_collection_str)
        .filterBounds(fc)
        .filterDate(start_date, end_date)
        .filter(ee.Filter.lte(const.CLOUDY_PIXEL_PERCENTAGE_STR, const.CLOUD_FILTER)))


    # Import and filter s2cloudless.
    s2_cloudless_col = (ee.ImageCollection(const.COPERNICUS_S2_CLOUD_PROBABILITY_STR)
        .filterBounds(fc)
        .filterDate(start_date, end_date))
    
    # Join the filtered s2cloudless collection to the SR collection by the 'system:index' property.
    return ee.ImageCollection(ee.Join.saveFirst(const.s2cloudless_str).apply(**{
        'primary': s2_sr_col,
        'secondary': s2_cloudless_col,
        'condition': ee.Filter.equals(**{
            'leftField': 'system:index',
            'rightField': 'system:index'
        })
    }))




# %% ../nbs/satellite_data/s2_masks.ipynb 5
def add_cloud_bands(img):
    # Get s2cloudless image, subset the probability band.
    cld_prb = ee.Image(img.get(const.s2cloudless_str)).select('probability')

    # Condition s2cloudless by the probability threshold value.
    is_cloud = cld_prb.gt(const.CLD_PRB_THRESH).rename(const.clouds_name_bands_str)

    # Add the cloud probability layer and cloud mask as image bands.
    return img.addBands(ee.Image([cld_prb, is_cloud]))
